pipeline {
    agent any
    stages {
        stage('Welcome Branch') {
            when {
                expression {
                    GIT_BRANCH == 'feature/test-jenkins-branch'
                }
            }
            steps {
                echo 'welcome to this pipeline'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
