pipeline {
    agent any
    stages {
        stage('Check Maven Installation') {
            steps {
                sh 'echo $PATH'
                sh 'which mvn'
            }
        }
        stage('Welcome') {
            steps {
                echo 'welcome to this pipeline'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
